/********************************************************************
* io/dcache/src/G__DCache.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error io/dcache/src/G__DCache.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__DCache();
extern void G__cpp_setup_inheritanceG__DCache();
extern void G__cpp_setup_typetableG__DCache();
extern void G__cpp_setup_memvarG__DCache();
extern void G__cpp_setup_globalG__DCache();
extern void G__cpp_setup_memfuncG__DCache();
extern void G__cpp_setup_funcG__DCache();
extern void G__set_cpp_environmentG__DCache();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TDCacheFile.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__DCacheLN_TClass;
extern G__linked_taginfo G__G__DCacheLN_TBuffer;
extern G__linked_taginfo G__G__DCacheLN_TDirectory;
extern G__linked_taginfo G__G__DCacheLN_TMemberInspector;
extern G__linked_taginfo G__G__DCacheLN_TObject;
extern G__linked_taginfo G__G__DCacheLN_TNamed;
extern G__linked_taginfo G__G__DCacheLN_TString;
extern G__linked_taginfo G__G__DCacheLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__DCacheLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__DCacheLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__DCacheLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__DCacheLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__DCacheLN_TFile;
extern G__linked_taginfo G__G__DCacheLN_TDirectoryFile;
extern G__linked_taginfo G__G__DCacheLN_TSystem;
extern G__linked_taginfo G__G__DCacheLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__DCacheLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__DCacheLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__G__DCacheLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__DCacheLN_EAccessMode;
extern G__linked_taginfo G__G__DCacheLN_FileStat_t;
extern G__linked_taginfo G__G__DCacheLN_TDCacheFile;
extern G__linked_taginfo G__G__DCacheLN_TDCacheFilecLcLstat64;
extern G__linked_taginfo G__G__DCacheLN_TDCacheFilecLcLEOnErrorAction;
extern G__linked_taginfo G__G__DCacheLN_TDCacheSystem;

/* STUB derived class for protected member access */
