/********************************************************************
* core/zip/src/G__Zip.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error core/zip/src/G__Zip.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableG__Zip();
extern void G__cpp_setup_inheritanceG__Zip();
extern void G__cpp_setup_typetableG__Zip();
extern void G__cpp_setup_memvarG__Zip();
extern void G__cpp_setup_globalG__Zip();
extern void G__cpp_setup_memfuncG__Zip();
extern void G__cpp_setup_funcG__Zip();
extern void G__set_cpp_environmentG__Zip();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Compression.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__ZipLN_type_info;
extern G__linked_taginfo G__G__ZipLN_TClass;
extern G__linked_taginfo G__G__ZipLN_TNamed;
extern G__linked_taginfo G__G__ZipLN_TVirtualIsAProxy;
extern G__linked_taginfo G__G__ZipLN_ROOT;
extern G__linked_taginfo G__G__ZipLN_ROOTcLcLTInitBehavior;
extern G__linked_taginfo G__G__ZipLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__ZipLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ZipLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__G__ZipLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__ZipLN_ROOTcLcLECompressionAlgorithm;

/* STUB derived class for protected member access */
